;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-delete
        evil-forward-char
        evil-previous-line
        evil-ret
        ))

(setq mc/cmds-to-run-once
      '(
        evil-backward-char
        evil-next-line
        ))
